name: mygo_img_picker
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.0
  flutter_overlay_window: ^0.4.5
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "icons/ic_launcher.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/data.json
